### ISSUE TITLE
Install PHP-CPP errors about C++

### ISSUE THREAD

**Issue by barensoft** [CopernicaMarketingSoftware/PHP-CPP#209]
Hello,
When I install php-cpp by g++ 4.8  have had a  success.
But when I install it by g++4.7.2 have had a failure.
errors : 
 [root@bogon PHP-CPP]# make
mkdir -p shared/common
mkdir -p shared/zend
/opt/centos/devtoolset-1.1/root/usr/bin/c++ -Wall -c -std=c++11 -fvisibility=hidden -DBUILDING_PHPCPP -g `php-config --includes` -fpic -o shared/zend/base.o zend/base.cpp
In file included from zend/includes.h:67:0,
                 from zend/base.cpp:8:
zend/../include/byval.h:53:13: error: looser throw specifier for ‘virtual Php::ByVal::~ByVal()’
In file included from zend/includes.h:66:0,
                 from zend/base.cpp:8:
zend/../include/argument.h:28:13: error:   overriding ‘virtual Php::Argument::~Argument() noexcept (true)’
In file included from zend/includes.h:68:0,
                 from zend/base.cpp:8:
zend/../include/byref.h:53:13: error: looser throw specifier for ‘virtual Php::ByRef::~ByRef()’
In file included from zend/includes.h:66:0,
                 from zend/base.cpp:8:
zend/../include/argument.h:28:13: error:   overriding ‘virtual Php::Argument::~Argument() noexcept (true)’
make: *** [shared/zend/base.o] Error 1

How do I fix it?

Need your help ,thank you!

**Comment by hugdx** [comment]
Some functions in php-cpp are only worked with g++ 4.8. so please compile with gcc >= 4.8.
 see more at ``https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/164``

**Comment by martijnotto** [comment]
As said, the solution is to use a more recent compiler.
