### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by wuros** [CopernicaMarketingSoftware/PHP-CPP#469]
In file included from zend/includes.h:120,
                 from zend/base.cpp:8:
zend/callable.h:224:15: error: 'zend_internal_arg_info' {aka 'struct _zend_internal_arg_info'} has no member named 'is_variadic'
  224 |         info->is_variadic = false;
      |               ^~~~~~~~~~~
zend/callable.h:227:15: error: 'zend_internal_arg_info' {aka 'struct _zend_internal_arg_info'} has no member named 'pass_by_reference'
  227 |         info->pass_by_reference = arg.byReference();
      |               ^~~~~~~~~~~~~~~~~
make: *** [Makefile:219: shared/zend/base.o] Error 1

**Comment by gnat42** [comment]
I've started working on this. I've gotten to the point of compilation. There are still a few things to do.
* There's one piece of code that I've simply commented out in callable.
    * [initial type default](https://github.com/NobletSolutions/PHP-CPP/commit/40f3c2804d3f4dc075e01bd6991a8c6f5d571585#diff-9cf4b7b6a07fd6f6c781b65f382378fcec4abf75d1a993ef0b0cf9fea85f8164R152)
    * [this particular place too](https://github.com/NobletSolutions/PHP-CPP/commit/40f3c2804d3f4dc075e01bd6991a8c6f5d571585#diff-0f8275bb78eb2bd896921fcee8ae1b373f6a53fb5848166c79d5b076731906dbR215)
* All of the changes to classimpl.h and classimpl.cpp won't work with anything other than PHP 8.0. If the project were still alive and they wanted it backward compatible its not hard to make it that way - however in my opinion I'd drop all the previous PHP versions because they are already supported and this library isn't getting much love so I figure stick with the released upstream and use whatever previous version worked with the PHP version you need it to. Any thoughts on that?

**Comment by gnat42** [comment]
I should say that even with all the issues I pointed out above, my extension compiled against this and ran without any problems at this point...

**Comment by EmielBruijntjes** [comment]
This library is still being maintained by us, but the reality is that our time is limited. Like everyone, we have more plans than time, and because PHP-CPP is good-enough for us now, PHP-CPP projects are not easily prioritized and included in sprint-goals. Apologies for that.

Some background info:

- We currently run on PHP 7.2, so for us (as initiator and owner of this project) we _at least_ need PHP-CPP to support this version.
- We do have the intention to switch to PHP 8, but this is likely to be delayed until we start using Ubuntu 22.04.
- Once we do make the switch, it will (probably) be a requirement for PHP-CPP to support 8 and 7.2 for at least a transition period.
- Other users of this library might want PHP-CPP to be usable with other versions (especially 7.4 as that is the version shipped with Ubuntu 20.04).

Your help is much appreciated. It saves us time later on. But if possible, could you make sure that PHP 7.2 (and possibly other versions) are being maintained too? If this is technically impossible (because the differences are too big), we could also make a completely new repository for just PHP 8 support (we for example also have a PHP-CPP-LEGACY repository for PHP 5 support, because one code base to support both 5 and 7 was too challenging).

**Comment by gnat42** [comment]
Hey @EmielBruijntjes 
    Thanks for jumping in on this. I *totally* get the time issues and don't get me wrong I'm grateful for this libraries existence so please don't take my comments as a slight or as saying I expect better 'service' from code you've made freely available! I appreciate the work you've all done and I appreciate the inability to move to something else. I will adjust my branch/patch so that it supports PHP 7.x as it isn't hard to do I just didn't know if the project was abandoned or just not getting as much love.

When I get the patch into a good enough state for a PR state I'll submit it. There are 2-3 areas where I could really use a bit of a hand knowing if its necessary or the proper way to do it in your library so hopefully someone there can spare 5-10 minutes to give me feedback on those areas when I've submitted the PR.

**Comment by EmielBruijntjes** [comment]
It would be very nice if you can send in a pull request, and also if your code would use the same coding styles as ours so that we can just fit it in.

If you have questions you ask them to me. I will do my best to help you, but I must say that it has been a while since I made this library, and back then it was a real pain in the back to find out how PHP works internally and to turn all those strange and undocumented structs into an object oriented and programmer-friendly C++ platform.

**Comment by gnat42** [comment]
I 1000% agree. 99% of my time was trying to find some kind of sensible changelog to see what should be different. PHP 7->8 was a massive change because they now have zend_object and zend_string instead of just zval and have zend_result and zend_type so more structs. The way I figured out what to change was by compiling over and over and then reading some failed piece and doing a git diff between the two php versions of some header file I thought would contain the differences I needed. the zend_object_handlers had by far the most changes and it wasn't until way late into the process that I found some of the changes I saw in the diffs in the UPGRADING.INTERNALS file php provided. 

I don't know if I need your help looking at the PHP side of things to be honest. I know of 2 or 3 areas where I though it would have been great to talk to the upstream developer of PHP-CPP. So once I submit the PR I'll try to highlight the areas I'm still wondering about.

With respect to coding style, is that documented anywhere? Is there a tool/config that I can use to do that automatically?

**Comment by EmielBruijntjes** [comment]
No there is no documentation about coding style, but I think that if you have read through the code for a while, that you will see the patterns. I really like adding a crazy amount of in-code comments (like almost every line) so that future developers (which might be me again) can see what you were thinking and doing.

**Comment by gnat42** [comment]
Ok, there's a PR now for this in #471

**Comment by wuros** [comment]
I try to build https://github.com/NobletSolutions/PHP-CPP.git and got error:

zend/extensionimpl.h:187:24: error: 'static zend_result Php::ExtensionImpl::processShutdown(int, int)' cannot be overloaded with 'static zend_result Php::ExtensionImpl::processShutdown(int, int)'
  187 |     static zend_result processShutdown(int type, int module_number);
      |                        ^~~~~~~~~~~~~~~
zend/extensionimpl.h:175:24: note: previous declaration 'static zend_result Php::ExtensionImpl::processShutdown(int, int)'
  175 |     static zend_result processShutdown(int type, int module_number);
      |                        ^~~~~~~~~~~~~~~
make: *** [Makefile:219: shared/zend/base.o] Error 1

**Comment by gnat42** [comment]
Hey @wuros yeah I did a bad job of converting my original changes to changes that worked with all versions of PHP, I've redone that work and pushed it but haven't tested that yet either

**Comment by wuros** [comment]
@gnat42 
I don't know how, but now I try re-make and final error changed to:

zend/classimpl.cpp:1140:44: error: cannot convert 'zend_object**' {aka '_zend_object**'} to 'zend_object*' {aka '_zend_object*'} in argument passing

Also I see other errors:

zend/classimpl.cpp:1055:31: error: request for member 'ce' in '* object', which is of pointer type 'zend_object*' {aka '_zend_object*'} (maybe you meant to use '->' ?)
 1055 |         auto *entry = object->ce;
      |                               ^~
zend/classimpl.cpp:1089:49: error: cannot convert 'zend_object**' {aka '_zend_object**'} to 'zend_object*' {aka '_zend_object*'} in argument passing
 1089 |         return std_object_handlers.has_property(object, name, has_set_exists, cache_slot);
      |                                                 ^~~~~~
      |                                                 |
      |                                                 zend_object** {aka _zend_object**}
zend/classimpl.cpp: In static member function 'static void Php::ClassImpl::unsetProperty(zend_object**, zend_string**, void**)':
zend/classimpl.cpp:1117:31: error: request for member 'ce' in '* object', which is of pointer type 'zend_object*' {aka '_zend_object*'} (maybe you meant to use '->' ?)
 1117 |         auto *entry = object->ce;//Z_OBJCE_P(object);
      |                               ^~
zend/classimpl.cpp:1129:92: error: no matching function for call to 'Php::ObjectImpl::find(zend_object**&)'
 1129 |         if (iter == impl->_properties.end()) impl->_base->callUnset(ObjectImpl::find(object)->object(), member);

**Comment by gnat42** [comment]
Good catch - I've fixed that one and pushed it again... It would probably be better if I could compile to test it instead of doing this slower remote compile through you but I'm not able to - give it another try

**Comment by gnat42** [comment]
Actually hold on.. more errors

**Comment by wuros** [comment]
@gnat42  I got this:

zend/classimpl.cpp:1143:44: error: cannot convert 'zend_object**' {aka '_zend_object**'} to 'zend_object*' {aka '_zend_object*'} in argument passing
 1143 |         std_object_handlers.unset_property(object, member, cache_slot);
      |                                            ^~~~~~
      |                                            |
      |                                            zend_object** {aka _zend_object**}
make: *** [Makefile:219: shared/zend/classimpl.o] Error 1

Also I see:

zend/classimpl.cpp:1055:31: error: request for member 'ce' in '* object', which is of pointer type 'zend_object*' {aka '_zend_object*'} (maybe you meant to use '->' ?)
 1055 |         auto *entry = object->ce;
      |                               ^~
zend/classimpl.cpp:1089:49: error: cannot convert 'zend_object**' {aka '_zend_object**'} to 'zend_object*' {aka '_zend_object*'} in argument passing
 1089 |         return std_object_handlers.has_property(object, name, has_set_exists, cache_slot);
      |                                                 ^~~~~~
      |                                                 |
      |                                                 zend_object** {aka _zend_object**}
zend/classimpl.cpp: In static member function 'static void Php::ClassImpl::unsetProperty(zend_object**, zend_string**, void**)':
zend/classimpl.cpp:1120:31: error: request for member 'ce' in '* object', which is of pointer type 'zend_object*' {aka '_zend_object*'} (maybe you meant to use '->' ?)
 1120 |         auto *entry = object->ce;
      |                               ^~
zend/classimpl.cpp:1132:92: error: no matching function for call to 'Php::ObjectImpl::find(zend_object**&)'
 1132 |         if (iter == impl->_properties.end()) impl->_base->callUnset(ObjectImpl::find(object)->object(), member);

I use php:8.0.0-fpm-alpine image and install apk add autoconf dpkg-dev dpkg file g++ gcc libc-dev make pkgconf openssl-dev re2c bzip2-dev libzip-dev zlib-dev icu-dev gmp gmp-dev git

**Comment by gnat42** [comment]
I just did a test compile with my latest version and it seems to compile now.

**Comment by mdumitrean** [comment]
gnat42 also reconcile fixes with stmboyd who did some cleanups on the PHP80 support.
we're currently using the PHP80 module and everything works great.

**Comment by gnat42** [comment]
Hey @mdumitrean thanks for the feedback.

From what I could see it worked for me as well. I'm still a *little* concerned about 4 areas I commented on in the PR. If @stmboyd or @EmielBruijntjes have a moment to weigh in. That'd be great. Obviously it won't get merged until someone at Coppernica is comfortable merging it but it would be good to know what they think of those areas and what I can/should do to improve/fix them.

**Comment by kirmorozov** [comment]
I've set up github actions for my fork, feel free to add php 8.0 to build matrix.
I believe I will have some time to add tests with phpunit and compilation of demo module
@EmielBruijntjes I think that your library is the best way to extend php with some runtime.

**Comment by wuros** [comment]
@gnat42 
While building I got error

#16 1.386 In file included from /usr/include/phpcpp.h:38,
#16 1.386                  from myext.cpp:1:
#16 1.386 /usr/include/phpcpp/throwable.h:29:1: error: expected class-name before '{' token
#16 1.386    29 | {
#16 1.386       | ^
#16 1.386 /usr/include/phpcpp/throwable.h: In constructor 'Php::Throwable::Throwable(const string&)':
#16 1.386 /usr/include/phpcpp/throwable.h:43:63: error: expected class-name before '(' token
#16 1.386    43 |     Throwable(const std::string &message) : std::runtime_error(message) {}
#16 1.386       |                                                               ^
#16 1.386 /usr/include/phpcpp/throwable.h:43:63: error: expected '{' before '(' token
#16 3.933 make: *** [Makefile:25: myext.o] Error 1

**Comment by gnat42** [comment]
Hello,  I remember hitting this once. If I'm not mistaken you need a newer version of gcc. ---- On Sat, 16 Jan 2021 09:04:08 -0700  notifications@github.com  wrote ----
@gnat42
While building I got error
#16 1.386 In file included from /usr/include/phpcpp.h:38,
#16 1.386                  from myext.cpp:1:
#16 1.386 /usr/include/phpcpp/throwable.h:29:1: error: expected class-name before '{' token
#16 1.386    29 | {
#16 1.386       | ^
#16 1.386 /usr/include/phpcpp/throwable.h: In constructor 'Php::Throwable::Throwable(const string&)':
#16 1.386 /usr/include/phpcpp/throwable.h:43:63: error: expected class-name before '(' token
#16 1.386    43 |     Throwable(const std::string &message) : std::runtime_error(message) {}
#16 1.386       |                                                               ^
#16 1.386 /usr/include/phpcpp/throwable.h:43:63: error: expected '{' before '(' token
#16 3.933 make: *** [Makefile:25: myext.o] Error 1

**Comment by wuros** [comment]
@gnat42 gcc (Alpine 10.2.1_pre1) 10.2.1 20201203
What should I do?

**Comment by gnat42** [comment]
Well that's definitely not it... Apologies but I don't know why you're getting that error.

**Comment by axelusarov** [comment]
Is there any chance that not all issues were fixed yet? When PHP constructors or destructors are explicitly declared I'm getting this fatal on PHP startup:
`PHP Fatal error:  Method MyClass::__construct() cannot declare a return type in Unknown on line 0`


```
customClass.method<&MyCustomClass::__construct>("__construct");
customClass.method<&MyCustomClass::__destruct>("__destruct");
```

**Comment by gnat42** [comment]
so I don't know if this has much to do with PHP8 support - I was pretty sure that you can't declare a return type for constructors in plain PHP itself so I wonder if that's the issue?

**Comment by axelusarov** [comment]
I'm wondering because the same code works smoothly with PHP74 using PHP-CPP master branch.

```cpp
// inside the MyCustomClass class
void __construct(Php::Parameters &params)
{
    std::cout << "MyCustomClass::__construct(" << params[0] << ")" << std::endl;
}

// ...

// export
extern "C" 
{
    PHPCPP_EXPORT void *get_module()
    {
        static Php::Extension extension("my_test_ext", "1.0");
        Php::Class<MyCustomClass> customClass("MyClass");
        
        customClass.method<&MyCustomClass::__construct>("__construct", Php::Public | Php::Final, {Php::ByVal("my_prop", Php::Type::Numeric)});
        
        extension.add(customClass);
        return extension;
    }
}
```

Then in test.php
```php
<?php

$class = new MyClass(42);

// output:

// MyCustomClass::MyCustomClass()
// MyCustomClass::__construct(42)
// MyCustomClass::__destruct
// MyCustomClass::~MyCustomClass
```

This example doesn't work in PHP8 when using the code from this PR.
`PHP Fatal error:  Method MyClass::__construct() cannot declare a return type in Unknown on line 0`

**Comment by axelusarov** [comment]
Now I left only `void __construct() {}` in my class, the results are the same.

**Comment by gnat42** [comment]
So I've looked at the project we have and don't get this error. The biggest difference is I'm not using `Php::Public | Php::Final`. For example here's a sample of mine.

```
//main.cpp
        // PdfText Methods =========================
        Php::Class<PdfText> pdfText("PdfText");
        pdfText.method<&PdfText::__construct>("__construct", Php::Public, {
            Php::ByVal("x", Php::Type::Numeric),
            Php::ByVal("y", Php::Type::Numeric),
            Php::ByVal("text", Php::Type::String),
            Php::ByVal("fontSize", Php::Type::Numeric, false),
            Php::ByVal("font", Php::Type::String, false)
        });
```
and the header

```
//pdf-text.h
class PdfText : public Php::Base {
private:
    int64_t x = 0;
    int64_t y = 0;
    //....
public:
    PdfText();
    PdfText(const PdfText &obj);
    void __construct(Php::Parameters &params);
    Php::Value getX();
    Php::Value getY();
    //...
};

```

Do we have any other significant differences in class definitions?

**Comment by axelusarov** [comment]
Here is the complete file I used for testing. It looks like the lib tries to assign "void" return type to php constructor method. I have no idea where and why. It seems I have to stick with PHP74 for a while :(
```cpp
#include <iostream>
#include <phpcpp.h>

class MyCustomClass : public Php::Base
{
private:
    int my_prop = 42;
public:
    MyCustomClass() {}
    MyCustomClass(const MyCustomClass &obj) {}
    void __construct(Php::Parameters &params) {
        this->my_prop = params[0];
    }
    Php::Value getProp() {
        return this->my_prop;
    }
};

extern "C" 
{
    PHPCPP_EXPORT void *get_module()
    {
        static Php::Extension extension("my_test_ext", "1.0");
        Php::Class<MyCustomClass> myCustomClass("MyCustomClass");

        myCustomClass.method<&MyCustomClass::__construct>("__construct", Php::Public, {
           Php::ByVal("my_prop", Php::Type::Numeric)
        });
        myCustomClass.method<&MyCustomClass::getProp>("getProp", Php::Public);
        
        extension.add(myCustomClass);
        return extension;
    }
}
```

**Comment by gnat42** [comment]
One last question, what version of PHP are you getting this issue on? I wonder if there's a break somewhere in a version of 8.0.x and I haven't compiled against it yet

**Comment by axelusarov** [comment]
I tried 2 different versions 8.0.1 and 8.0.9

**Comment by axelusarov** [comment]
Seems like I found the reason.
Please look at this file `zend/callable.cpp`
line 160: `info->type = (zend_type)ZEND_TYPE_INIT_CODE((int)_return, true, 0);`

I added this check and the issue gone finally.
```cpp
void Callable::initialize(zend_internal_function_info *info, const char *classname) const
{
    // ...
    if ((int)_return) { // Type::Undefined ?
        info->type = (zend_type)ZEND_TYPE_INIT_CODE((int)_return, true, 0);
    }
    // ...
}

**Comment by gnat42** [comment]
Thanks for digging into that. I'll take a bit of a look and add it to the patch soon

**Comment by henrywood** [comment]
I was wondering if someone can tell me how far away we are from PHP 8.0 support ?

I just tried building the with the PR of @gnat42 but I get this error:

zend/classimpl.cpp: In member function ‘zend_object_handlers* Php::ClassImpl::objectHandlers()’:
zend/classimpl.cpp:373:27: error: invalid conversion from ‘int (*)(zval*, zend_class_entry**, zend_function**, zend_object**, zend_bool) {aka int (*)(_zval_struct*, _zend_class_entry**, _zend_function**, _zend_object**, unsigned char)}’ to ‘zend_object_get_closure_t {aka int (*)(_zval_struct*, _zend_class_entry**, _zend_function**, _zend_object**)}’ [-fpermissive]
     _handlers.get_closure = &ClassImpl::getClosure;

Thanks to @gnat42 for his work on this PR !

**Comment by henrywood** [comment]
Adding a simple cast makes it compile:

´´´
_handlers.get_closure = (zend_object_get_closure_t) &ClassImpl::getClosure;
´´´

**Comment by gengpei** [comment]
@gnat42 
Hi, my env is php:8.0.11 macos: 11.6, I found it will randomly crush in php-src's file zend_API.c at line 2379 or 2479,  
and the crush reason is in php-cpp's file callable.h line 38.
```c++
_argv(new zend_internal_arg_info[_argc + 2])
```
there is no initialization for _argv[0], and _argv[0].type filled with random content, and lead to crush.
Hope u can fix it, thanks.
my test code as following:
``` c++
    // create extension
    static Php::Extension extension("xxx","1.0");

    static Php::Namespace ns("Xxx");
    // add function to namespace
    ns.add<func>("func", {
            Php::ByVal("a", Php::Type::Array),
            Php::ByVal("b", Php::Type::Array),
    });

    // add the namespace to the extension
    extension.add(ns);

    // return the extension module
    return extension.module();
```

**Comment by edhelas** [comment]
Hi, I was wondering about the status of this pull-request and about its compatibility with the current PHP 8.1 version?

**Comment by gnat42** [comment]
Hello @edhelas,

  From what I understand Copernica's product uses PHP 7.x so there isn't a lot of time/effort to support 8.x. However I think they're moving there so this will eventually get merged or used somehow. There are some changes needed to get php 8.1 working. I know someone submitted another patch needed that I've applied to my version of this PR used to build for 8.1. Seemed to work well. I can't recall if I created a PR with both. Let me know if you'd like the php8.1 patch as well.

**Comment by edhelas** [comment]
Hi @gnat42. Thanks for the quick answer :) 
I'm currently trying the 8.1 patch and will come back to you with my feedback once I'm done.

**Comment by carlos-granados** [comment]
There is a maintained fork which has been updated to PHP 8.2. You can find it here: https://github.com/fast-debug/PHP-CPP

**Comment by robocoder** [comment]
Fixed in PHP-CPP 2.4.0 (3d791e05c2655facc556d89565ead4f71c4c6217)

**Comment by EmielBruijntjes** [comment]
Closing this as this has apparently been fixed.
