### ISSUE TITLE
Can't compile for php7

### ISSUE THREAD

**Issue by zecho** [CopernicaMarketingSoftware/PHP-CPP#240]
$ make
mkdir -p shared/common
mkdir -p shared/zend
g++ -Wall -c -std=c++11 -fvisibility=hidden -DBUILDING_PHPCPP -Wno-write-strings -g `php-config --includes` -fpic -o shared/zend/inivalue.o zend/inivalue.cpp
In file included from zend/includes.h:130:0,
                 from zend/inivalue.cpp:8:
zend/constantimpl.h:85:53: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
         ZVAL_STRINGL(&_constant.value, value, len, 0);
                                                     ^
zend/constantimpl.h:96:65: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
         ZVAL_STRINGL(&_constant.value, value, ::strlen(value), 0);
                                                                 ^
zend/constantimpl.h:107:70: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
         ZVAL_STRINGL(&_constant.value, value.c_str(), value.size(), 0);
                                                                      ^
In file included from zend/includes.h:104:0,
                 from zend/inivalue.cpp:8:
zend/callable.h: In member function ‘void Php::Callable::fill(zend_arg_info*, const Php::Argument&) const’:
zend/callable.h:146:20: error: cannot convert ‘const char*’ to ‘zend_string* {aka _zend_string*}’ in assignment
         info->name = arg.name();
                    ^
zend/callable.h:147:15: error: ‘zend_arg_info {aka struct _zend_arg_info}’ has no member named ‘name_len’
         info->name_len = ::strlen(arg.name());
               ^
zend/callable.h:179:26: error: cannot convert ‘const char*’ to ‘zend_string* {aka _zend_string*}’ in assignment
         info->class_name = arg.type() == Type::Object ? arg.classname() : nullptr;
                          ^
zend/callable.h:180:15: error: ‘zend_arg_info {aka struct _zend_arg_info}’ has no member named ‘class_name_len’
         info->class_name_len = arg.type() == Type::Object && arg.classname() ? ::strlen(arg.classname()) : 0;
               ^
In file included from zend/includes.h:118:0,
                 from zend/inivalue.cpp:8:
zend/hashiterator.h: In constructor ‘Php::HashIterator::HashIterator(HashTable*, bool, bool)’:
zend/hashiterator.h:38:67: error: cannot convert ‘Bucket** {aka _Bucket**}’ to ‘HashPosition* {aka unsigned int*}’ for argument ‘2’ to ‘void zend_hash_internal_pointer_reset_ex(HashTable*, HashPosition*)’
             zend_hash_internal_pointer_reset_ex(_table, &_position);
                                                                   ^
zend/hashiterator.h: In member function ‘virtual bool Php::HashIterator::increment()’:
zend/hashiterator.h:91:57: error: cannot convert ‘Bucket** {aka _Bucket**}’ to ‘HashPosition* {aka unsigned int*}’ for argument ‘2’ to ‘int zend_hash_move_forward_ex(HashTable*, HashPosition*)’
         if (zend_hash_move_forward_ex(_table, &_position) == SUCCESS)
                                                         ^
zend/hashiterator.h: In member function ‘virtual bool Php::HashIterator::decrement()’:
zend/hashiterator.h:119:65: error: cannot convert ‘Bucket** {aka _Bucket**}’ to ‘HashPosition* {aka unsigned int*}’ for argument ‘2’ to ‘void zend_hash_internal_pointer_end_ex(HashTable*, HashPosition*)’
             zend_hash_internal_pointer_end_ex(_table, &_position);
                                                                 ^
zend/hashiterator.h:121:64: error: cannot convert ‘Bucket** {aka _Bucket**}’ to ‘HashPosition* {aka unsigned int*}’ for argument ‘2’ to ‘int zend_hash_move_backwards_ex(HashTable*, HashPosition*)’
         else if (zend_hash_move_backwards_ex(_table, &_position) == FAILURE)
                                                                ^
zend/hashiterator.h: In member function ‘bool Php::HashIterator::read()’:
zend/hashiterator.h:194:71: error: cannot convert ‘Bucket** {aka _Bucket**}’ to ‘HashPosition* {aka unsigned int*}’ for argument ‘3’ to ‘void zend_hash_get_current_key_zval_ex(const HashTable*, zval*, HashPosition*)’
         zend_hash_get_current_key_zval_ex(_table, key._val, &_position);
                                                                       ^
zend/hashiterator.h:225:75: error: cannot convert ‘void**’ to ‘HashPosition* {aka unsigned int*}’ for argument ‘2’ to ‘zval* zend_hash_get_current_data_ex(HashTable*, HashPosition*)’
         zend_hash_get_current_data_ex(_table, (void **) &value, &_position);
                                                                           ^
In file included from zend/includes.h:120:0,
                 from zend/inivalue.cpp:8:
zend/traverseiterator.h: In constructor ‘Php::TraverseIterator::TraverseIterator(zval*, bool)’:
zend/traverseiterator.h:35:60: error: ‘zend_get_class_entry’ was not declared in this scope
         auto *entry = zend_get_class_entry(object TSRMLS_CC);
                                                            ^
zend/traverseiterator.h: In member function ‘bool Php::TraverseIterator::read()’:
zend/traverseiterator.h:231:62: error: too many arguments to function
         _iter->funcs->get_current_data(_iter, &zval TSRMLS_CC);
                                                              ^
In file included from zend/includes.h:121:0,
                 from zend/inivalue.cpp:8:
zend/iteratorimpl.h: In constructor ‘Php::IteratorImpl::IteratorImpl(Php::Iterator*)’:
zend/iteratorimpl.h:167:20: error: no match for ‘operator=’ (operand types are ‘zval {aka _zval_struct}’ and ‘Php::IteratorImpl*’)
         _impl.data = this;
                    ^
In file included from /usr/include/php/20151012/Zend/zend.h:31:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from zend/includes.h:36,
                 from zend/inivalue.cpp:8:
/usr/include/php/20151012/Zend/zend_types.h:121:8: note: candidate: _zval_struct& _zval_struct::operator=(const _zval_struct&)
 struct _zval_struct {
        ^
/usr/include/php/20151012/Zend/zend_types.h:121:8: note:   no known conversion for argument 1 from ‘Php::IteratorImpl*’ to ‘const _zval_struct&’
/usr/include/php/20151012/Zend/zend_types.h:121:8: note: candidate: _zval_struct& _zval_struct::operator=(_zval_struct&&)
/usr/include/php/20151012/Zend/zend_types.h:121:8: note:   no known conversion for argument 1 from ‘Php::IteratorImpl*’ to ‘_zval_struct&&’
In file included from zend/includes.h:122:0,
                 from zend/inivalue.cpp:8:
zend/classimpl.h: At global scope:
zend/classimpl.h:179:12: error: ‘zend_object_value’ does not name a type
     static zend_object_value createObject(zend_class_entry *entry TSRMLS_DC);
            ^
zend/classimpl.h:180:12: error: ‘zend_object_value’ does not name a type
     static zend_object_value cloneObject(zval *val TSRMLS_DC);
            ^
In file included from zend/includes.h:122:0,
                 from zend/inivalue.cpp:8:
zend/classimpl.h:254:73: error: ‘zend_literal’ does not name a type
     static zval *readProperty(zval *object, zval *name, int type, const zend_literal *key TSRMLS_DC);
                                                                         ^
zend/classimpl.h:269:76: error: ‘zend_literal’ does not name a type
     static void writeProperty(zval *object, zval *name, zval *value, const zend_literal *key TSRMLS_DC);
                                                                            ^
zend/classimpl.h:283:80: error: ‘zend_literal’ does not name a type
     static int hasProperty(zval *object, zval *name, int has_set_exists, const zend_literal *key TSRMLS_DC);
                                                                                ^
zend/classimpl.h:295:65: error: ‘zend_literal’ does not name a type
     static void unsetProperty(zval *object, zval *member, const zend_literal *key TSRMLS_DC);
                                                                 ^
zend/classimpl.h:310:92: error: ‘zend_literal’ does not name a type
     static zend_function *getMethod(zval **object_ptr, char *method, int method_len, const zend_literal *key TSRMLS_DC);
                                                                                            ^
In file included from zend/includes.h:123:0,
                 from zend/inivalue.cpp:8:
zend/objectimpl.h: In constructor ‘Php::ObjectImpl::ObjectImpl(zend_class_entry*, Php::Base*, int)’:
zend/objectimpl.h:119:50: error: ‘zend_objects_store_dtor_t’ was not declared in this scope
         _handle = zend_objects_store_put(php(), (zend_objects_store_dtor_t)destructMethod, (zend_objects_free_object_storage_t)freeMethod, NULL
                                                  ^
zend/objectimpl.h:119:93: error: ‘zend_objects_free_object_storage_t’ was not declared in this scope
         _handle = zend_objects_store_put(php(), (zend_objects_store_dtor_t)destructMethod, (zend_objects_free_object_storage_t)freeMethod, NULL
                                                                                             ^
zend/objectimpl.h:122:70: error: request for member ‘bucket’ in ‘*(executor_globals._zend_executor_globals::objects_store._zend_objects_store::object_buckets + ((sizetype)(((long unsigned int)((Php::ObjectImpl*)this)->Php::ObjectImpl::_handle) * 8ul)))’, which is of pointer type ‘zend_object* {aka _zend_object*}’ (maybe you meant to use ‘->’ ?)
         if (refcount != 1) EG(objects_store).object_buckets[_handle].bucket.obj.refcount = refcount;
                                                                      ^
zend/objectimpl.h: In member function ‘void Php::ObjectImpl::destruct()’:
zend/objectimpl.h:144:57: error: ‘zend_objects_free_object_storage’ was not declared in this scope
         zend_objects_free_object_storage(php() TSRMLS_CC);
                                                         ^
zend/objectimpl.h: In static member function ‘static Php::ObjectImpl* Php::ObjectImpl::find(zval*)’:
zend/objectimpl.h:159:88: error: ‘zend_object_store_get_object’ was not declared in this scope
         MixedObject *object = (MixedObject *)zend_object_store_get_object(val TSRMLS_CC);
                                                                                        ^
In file included from zend/includes.h:124:0,
                 from zend/inivalue.cpp:8:
zend/parametersimpl.h: In constructor ‘Php::ParametersImpl::ParametersImpl(zval*, int)’:
zend/parametersimpl.h:36:63: error: ‘zend_vm_stack_top’ was not declared in this scope
             zval **arg = (zval **) (zend_vm_stack_top(TSRMLS_C) - 1 - (argc-i));
                                                               ^
In file included from zend/includes.h:126:0,
                 from zend/inivalue.cpp:8:
zend/compileroptions.h: At global scope:
zend/compileroptions.h:27:5: error: ‘zend_uint’ does not name a type
     zend_uint _original;
     ^
zend/compileroptions.h:42:31: error: expected ‘)’ before ‘options’
     CompilerOptions(zend_uint options TSRMLS_DC)
                               ^
zend/compileroptions.h: In destructor ‘virtual Php::CompilerOptions::~CompilerOptions()’:
zend/compileroptions.h:62:32: error: ‘_original’ was not declared in this scope
         CG(compiler_options) = _original;
                                ^
In file included from /usr/include/php/20151012/Zend/zend_globals.h:28:0,
                 from /usr/include/php/20151012/Zend/zend_compile.h:657,
                 from /usr/include/php/20151012/Zend/zend_modules.h:26,
                 from /usr/include/php/20151012/Zend/zend_API.h:27,
                 from /usr/include/php/20151012/main/php.h:40,
                 from zend/includes.h:36,
                 from zend/inivalue.cpp:8:
zend/executestate.h: In constructor ‘Php::ExecuteState::ExecuteState(int)’:
zend/executestate.h:63:28: error: ‘zend_executor_globals {aka struct _zend_executor_globals}’ has no member named ‘active_op_array’
         _active_op_array = EG(active_op_array);
                            ^
zend/executestate.h:64:33: error: ‘zend_executor_globals {aka struct _zend_executor_globals}’ has no member named ‘return_value_ptr_ptr’
         _return_value_ptr_ptr = EG(return_value_ptr_ptr);
                                 ^
zend/executestate.h:65:23: error: ‘zend_executor_globals {aka struct _zend_executor_globals}’ has no member named ‘opline_ptr’
         _opline_ptr = EG(opline_ptr);
                       ^
zend/executestate.h:66:24: error: ‘struct _zend_compiler_globals’ has no member named ‘interactive’
         _interactive = CG(interactive);
                        ^
zend/executestate.h: In destructor ‘virtual Php::ExecuteState::~ExecuteState()’:
zend/executestate.h:81:9: error: ‘struct _zend_compiler_globals’ has no member named ‘interactive’
         CG(interactive) = _interactive;
         ^
zend/executestate.h:83:9: error: ‘zend_executor_globals {aka struct _zend_executor_globals}’ has no member named ‘opline_ptr’
         EG(opline_ptr) = _opline_ptr;
         ^
zend/executestate.h:84:9: error: ‘zend_executor_globals {aka struct _zend_executor_globals}’ has no member named ‘active_op_array’
         EG(active_op_array) = _active_op_array;
         ^
zend/executestate.h:85:9: error: ‘zend_executor_globals {aka struct _zend_executor_globals}’ has no member named ‘return_value_ptr_ptr’
         EG(return_value_ptr_ptr) = _return_value_ptr_ptr;
         ^
zend/opcodes.h: In member function ‘Php::Value Php::Opcodes::execute() const’:
zend/opcodes.h:81:9: error: ‘zend_executor_globals {aka struct _zend_executor_globals}’ has no member named ‘return_value_ptr_ptr’
         EG(return_value_ptr_ptr) = &retval_ptr;
         ^
zend/opcodes.h:82:9: error: ‘zend_executor_globals {aka struct _zend_executor_globals}’ has no member named ‘active_op_array’
         EG(active_op_array) = _opcodes;
         ^
zend/opcodes.h:84:14: error: ‘zend_executor_globals {aka struct _zend_executor_globals}’ has no member named ‘active_symbol_table’
         if (!EG(active_symbol_table)) zend_rebuild_symbol_table(TSRMLS_C);
              ^
zend/opcodes.h:85:9: error: ‘struct _zend_compiler_globals’ has no member named ‘interactive’
         CG(interactive) = 0;
         ^
zend/opcodes.h:88:30: error: cannot convert ‘zend_object* {aka _zend_object*}’ to ‘zval* {aka _zval_struct*}’ in initialization
         zval* oldException = EG(exception);
                              ^
In file included from zend/includes.h:128:0,
                 from zend/inivalue.cpp:8:
zend/opcodes.h:91:40: error: too few arguments to function ‘void zend_execute(zend_op_array*, zval*)’
         zend_execute(_opcodes TSRMLS_CC);
                                        ^
In file included from /usr/include/php/20151012/Zend/zend_API.h:31:0,
                 from /usr/include/php/20151012/main/php.h:40,
                 from zend/includes.h:36,
                 from zend/inivalue.cpp:8:
/usr/include/php/20151012/Zend/zend_execute.h:41:15: note: declared here
 ZEND_API void zend_execute(zend_op_array *op_array, zval *return_value);
               ^
In file included from /usr/include/php/20151012/Zend/zend_globals.h:28:0,
                 from /usr/include/php/20151012/Zend/zend_compile.h:657,
                 from /usr/include/php/20151012/Zend/zend_modules.h:26,
                 from /usr/include/php/20151012/Zend/zend_API.h:27,
                 from /usr/include/php/20151012/main/php.h:40,
                 from zend/includes.h:36,
                 from zend/inivalue.cpp:8:
zend/opcodes.h:95:29: error: comparison between distinct pointer types ‘zval* {aka _zval_struct*}’ and ‘zend_object* {aka _zend_object*}’ lacks a cast
         if (oldException != EG(exception) && EG(exception)) throw OrigException(EG(exception) TSRMLS_CC);
                             ^
In file included from zend/includes.h:128:0,
                 from zend/inivalue.cpp:8:
zend/opcodes.h:95:104: error: no matching function for call to ‘Php::OrigException::OrigException(zend_object*&)’
         if (oldException != EG(exception) && EG(exception)) throw OrigException(EG(exception) TSRMLS_CC);
                                                                                                        ^
In file included from zend/includes.h:114:0,
                 from zend/inivalue.cpp:8:
zend/origexception.h:73:5: note: candidate: Php::OrigException::OrigException(Php::OrigException&&)
     OrigException(OrigException &&exception) :
     ^
zend/origexception.h:73:5: note:   no known conversion for argument 1 from ‘zend_object* {aka _zend_object*}’ to ‘Php::OrigException&&’
zend/origexception.h:60:5: note: candidate: Php::OrigException::OrigException(const Php::OrigException&)
     OrigException(const OrigException &exception) : 
     ^
zend/origexception.h:60:5: note:   no known conversion for argument 1 from ‘zend_object* {aka _zend_object*}’ to ‘const Php::OrigException&’
zend/origexception.h:47:5: note: candidate: Php::OrigException::OrigException(zval*)
     OrigException(zval *val TSRMLS_DC) : 
     ^
zend/origexception.h:47:5: note:   no known conversion for argument 1 from ‘zend_object* {aka _zend_object*}’ to ‘zval* {aka _zval_struct*}’
In file included from /usr/include/php/20151012/Zend/zend.h:39:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from zend/includes.h:36,
                 from zend/inivalue.cpp:8:
zend/opcodes.h:105:9: error: cannot convert ‘zval** {aka _zval_struct**}’ to ‘zval* {aka _zval_struct*}’ for argument ‘1’ to ‘void _zval_ptr_dtor(zval*)’
         zval_ptr_dtor(&retval_ptr);
         ^
In file included from zend/includes.h:130:0,
                 from zend/inivalue.cpp:8:
zend/constantimpl.h: In constructor ‘Php::ConstantImpl::ConstantImpl(const char*, const char*, size_t)’:
zend/constantimpl.h:85:9: error: ‘ZVAL_STRINGL’ was not declared in this scope
         ZVAL_STRINGL(&_constant.value, value, len, 0);
         ^
zend/constantimpl.h: In constructor ‘Php::ConstantImpl::ConstantImpl(const char*, const char*)’:
zend/constantimpl.h:96:9: error: ‘ZVAL_STRINGL’ was not declared in this scope
         ZVAL_STRINGL(&_constant.value, value, ::strlen(value), 0);
         ^
zend/constantimpl.h: In constructor ‘Php::ConstantImpl::ConstantImpl(const char*, const string&)’:
zend/constantimpl.h:107:9: error: ‘ZVAL_STRINGL’ was not declared in this scope
         ZVAL_STRINGL(&_constant.value, value.c_str(), value.size(), 0);
         ^
zend/constantimpl.h: In member function ‘void Php::ConstantImpl::addTo(Php::ClassBase&) const’:
zend/constantimpl.h:140:14: error: ‘IS_BOOL’ was not declared in this scope
         case IS_BOOL:
              ^
zend/constantimpl.h:142:56: error: ‘Z_BVAL’ was not declared in this scope
             clss.property(_name, Z_BVAL(_constant.value), Php::Const);
                                                        ^
zend/constantimpl.h: In member function ‘void Php::ConstantImpl::initialize(const string&, int)’:
zend/constantimpl.h:184:23: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name_len = prefix.size() + 1 + namelen + 1;
                       ^
In file included from /usr/include/php/20151012/Zend/zend.h:33:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from zend/includes.h:36,
                 from zend/inivalue.cpp:8:
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
zend/constantimpl.h:185:38: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = (char *)emalloc(_constant.name_len);
                                      ^
In file included from zend/includes.h:130:0,
                 from zend/inivalue.cpp:8:
zend/constantimpl.h:188:68: error: cannot convert ‘zend_string* {aka _zend_string*}’ to ‘char*’ for argument ‘1’ to ‘char* strncpy(char*, const char*, size_t)’
             ::strncpy(_constant.name, prefix.c_str(), prefix.size());
                                                                    ^
zend/constantimpl.h:189:62: error: cannot convert ‘zend_string* {aka _zend_string*}’ to ‘char*’ for argument ‘1’ to ‘char* strncpy(char*, const char*, size_t)’
             ::strncpy(_constant.name + prefix.size(), "\\", 1);
                                                              ^
zend/constantimpl.h:190:77: error: cannot convert ‘zend_string* {aka _zend_string*}’ to ‘char*’ for argument ‘1’ to ‘char* strncpy(char*, const char*, size_t)’
             ::strncpy(_constant.name + prefix.size() + 1, _name, namelen + 1);
                                                                             ^
zend/constantimpl.h:195:23: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name_len = ::strlen(_name) + 1;
                       ^
zend/constantimpl.h:196:60: error: ‘zend_constant {aka struct _zend_constant}’ has no member named ‘name_len’
             _constant.name = zend_strndup(_name, _constant.name_len - 1);
                                                            ^
Makefile:197: recipe for target 'shared/zend/inivalue.o' failed
make: *** [shared/zend/inivalue.o] Error 1

**Comment by thierrylamarre** [comment]
Hi there,
I'm also interested in php7 support.
Is there any kind of rough timeline of when php7 support would be added?
I'm trying to see if I should wait for support in php-cpp or rewrite the extension without it.
Thanks!

**Comment by goddanao** [comment]
+1

**Comment by Samer-Al-iraqi** [comment]
+1

**Comment by MI-LA01** [comment]
+1

**Comment by atvise** [comment]
+1

**Comment by Shahelm** [comment]
+1

**Comment by swapniel99** [comment]
+1

**Comment by qhgongzi** [comment]
+1

**Comment by PiXeL0815** [comment]
+1

**Comment by oligriffiths** [comment]
+1

**Comment by omi-alex** [comment]
:+1

**Comment by martijnotto** [comment]
Please try the current master branch. It has been updated to work with PHP 7.0 and upwards. Should you encounter any issues (not unlikely!), please do not feel shy to open an issue.

**Comment by parsibox** [comment]
this error is for 2 php version
you most only have php 7

**Comment by TemaSM** [comment]
**For people from google:**
If you have installed multiple versions of php on your system, then remove others, just to leave only one installed (I did removed `php-8.0` in favor of `php-7.4`), then clone repository again and run make
