### ISSUE TITLE
Build fail after upgrading PHP package to 7.4.6 (PHP-CPP 2.2.0)

### ISSUE THREAD

**Issue by rozmanro1** [CopernicaMarketingSoftware/PHP-CPP#444]
Hi all,

I'm using custom linux kernel. Build with Buildroot.
kernel version - 4.19.19, buildroot version 2019.02.7

PHP-CPP version - 2.2.0
PHP - until recently , 7.1.18.

Today i upgraded the PHP package to the latest 7.4.6 version.

The PHP package is built & compiled succesfully.
But the PHP-CPP is failing during build and give me these errors:

================================================================================================================================
In file included from zend/includes.h:150:0,
                 from zend/callable.cpp:9:
zend/symbol.h: In constructor ‘Php::Symbol<T(Arguments ...)>::Symbol(void*, const char*)’:
zend/symbol.h:102:56: error: there are no arguments to ‘DL_FETCH_SYMBOL’ that depend on a template parameter, so a declaration of ‘DL_FETCH_SYMBO ’ must be available [-fpermissive]
         _method(DL_FETCH_SYMBOL((DL_HANDLE)handle, name)) {}
                                                        ^
zend/symbol.h:102:56: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from zend/includes.h:151:0,
                 from zend/callable.cpp:9:
zend/module.h: In destructor ‘virtual Php::Module::Persistent::~Persistent()’:
**zend/module.h:78:32: error: ‘DL_UNLOAD’ was not declared in this scope
                 DL_UNLOAD(*iter);**
                                ^
zend/module.h: In member function ‘void Php::Module::Persistent::add(const char*)’:
**zend/module.h:102:43: error: ‘DL_LOAD’ was not declared in this scope
             _handles.insert(DL_LOAD(module));**
                                           ^
zend/module.h: In constructor ‘Php::Module::Module(const char*, bool)’:
zend/module.h:129:31: error: ‘DL_LOAD’ was not declared in this scope
         _handle = DL_LOAD(path);
                               ^
zend/module.h: In destructor ‘virtual Php::Module::~Module()’:
zend/module.h:154:48: error: ‘DL_UNLOAD’ was not declared in this scope
       if (_handle) DL_UNLOAD((DL_HANDLE)_handle);
                                                ^
In file included from zend/includes.h:150:0,
                 from zend/base.cpp:8:
zend/symbol.h: In constructor ‘Php::Symbol<T(Arguments ...)>::Symbol(void*, const char*)’:
zend/symbol.h:102:56: error: there are no arguments to ‘DL_FETCH_SYMBOL’ that depend on a template parameter, so a declaration of ‘DL_FETCH_SYMBO ’ must be available [-fpermissive]
         _method(DL_FETCH_SYMBOL((DL_HANDLE)handle, name)) {}
                                                        ^
zend/symbol.h:102:56: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from zend/includes.h:151:0,
                 from zend/base.cpp:8:
zend/module.h: In destructor ‘virtual Php::Module::Persistent::~Persistent()’:
zend/module.h:78:32: error: ‘DL_UNLOAD’ was not declared in this scope
                 DL_UNLOAD(*iter);
                                ^
zend/module.h: In member function ‘void Php::Module::Persistent::add(const char*)’:
zend/module.h:102:43: error: ‘DL_LOAD’ was not declared in this scope
             _handles.insert(DL_LOAD(module));
                                           ^
zend/module.h: In constructor ‘Php::Module::Module(const char*, bool)’:
zend/module.h:129:31: error: ‘DL_LOAD’ was not declared in this scope
         _handle = DL_LOAD(path);
                               ^
zend/module.h: In destructor ‘virtual Php::Module::~Module()’:
zend/module.h:154:48: error: ‘DL_UNLOAD’ was not declared in this scope
       if (_handle) DL_UNLOAD((DL_HANDLE)_handle);
                                                ^
In file included from zend/includes.h:150:0,
                 from zend/classbase.cpp:9:
zend/symbol.h: In constructor ‘Php::Symbol<T(Arguments ...)>::Symbol(void*, const char*)’:
zend/symbol.h:102:56: error: there are no arguments to ‘DL_FETCH_SYMBOL’ that depend on a template parameter, so a declaration of ‘DL_FETCH_SYMBO ’ must be available [-fpermissive]
         _method(DL_FETCH_SYMBOL((DL_HANDLE)handle, name)) {}
                                                        ^
zend/symbol.h:102:56: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from zend/includes.h:151:0,
                 from zend/classbase.cpp:9:
zend/module.h: In destructor ‘virtual Php::Module::Persistent::~Persistent()’:
zend/module.h:78:32: error: ‘DL_UNLOAD’ was not declared in this scope
                 DL_UNLOAD(*iter);
                                ^
zend/module.h: In member function ‘void Php::Module::Persistent::add(const char*)’:
zend/module.h:102:43: error: ‘DL_LOAD’ was not declared in this scope
             _handles.insert(DL_LOAD(module));
                                           ^
zend/module.h: In constructor ‘Php::Module::Module(const char*, bool)’:
zend/module.h:129:31: error: ‘DL_LOAD’ was not declared in this scope
         _handle = DL_LOAD(path);
                               ^
zend/module.h: In destructor ‘virtual Php::Module::~Module()’:
zend/module.h:154:48: error: ‘DL_UNLOAD’ was not declared in this scope
       if (_handle) DL_UNLOAD((DL_HANDLE)_handle);
                                                ^
In file included from zend/includes.h:150:0,
                 from zend/callable.cpp:9:
zend/symbol.h: In instantiation of ‘Php::Symbol<T(Arguments ...)>::Symbol(void*, const char*) [with T = _zend_module_entry*; Arguments = {}]’:
zend/module.h:139:70:   required from here
zend/symbol.h:102:32: error: ‘DL_FETCH_SYMBOL’ was not declared in this scope
         _method(DL_FETCH_SYMBOL((DL_HANDLE)handle, name)) {}
                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from zend/includes.h:150:0,
                 from zend/classbase.cpp:9:
zend/symbol.h: In instantiation of ‘Php::Symbol<T(Arguments ...)>::Symbol(void*, const char*) [with T = _zend_module_entry*; Arguments = {}]’:
zend/module.h:139:70:   required from here
zend/symbol.h:102:32: error: ‘DL_FETCH_SYMBOL’ was not declared in this scope
         _method(DL_FETCH_SYMBOL((DL_HANDLE)handle, name)) {}
                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from zend/includes.h:150:0,
                 from zend/base.cpp:8:
zend/symbol.h: In instantiation of ‘Php::Symbol<T(Arguments ...)>::Symbol(void*, const char*) [with T = _zend_module_entry*; Arguments = {}]’:
zend/module.h:139:70:   required from here
zend/symbol.h:102:32: error: ‘DL_FETCH_SYMBOL’ was not declared in this scope
         _method(DL_FETCH_SYMBOL((DL_HANDLE)handle, name)) {}
                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from zend/includes.h:150:0,
                 from zend/constant.cpp:9:
zend/symbol.h: In constructor ‘Php::Symbol<T(Arguments ...)>::Symbol(void*, const char*)’:
zend/symbol.h:102:56: error: there are no arguments to ‘DL_FETCH_SYMBOL’ that depend on a template parameter, so a declaration of ‘DL_FETCH_SYMBO ’ must be available [-fpermissive]
         _method(DL_FETCH_SYMBOL((DL_HANDLE)handle, name)) {}
                                                        ^
zend/symbol.h:102:56: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from zend/includes.h:151:0,
                 from zend/constant.cpp:9:
zend/module.h: In destructor ‘virtual Php::Module::Persistent::~Persistent()’:
zend/module.h:78:32: error: ‘DL_UNLOAD’ was not declared in this scope
                 DL_UNLOAD(*iter);
                                ^
zend/module.h: In member function ‘void Php::Module::Persistent::add(const char*)’:
zend/module.h:102:43: error: ‘DL_LOAD’ was not declared in this scope
             _handles.insert(DL_LOAD(module));
                                           ^
zend/module.h: In constructor ‘Php::Module::Module(const char*, bool)’:
zend/module.h:129:31: error: ‘DL_LOAD’ was not declared in this scope
         _handle = DL_LOAD(path);
                               ^
zend/module.h: In destructor ‘virtual Php::Module::~Module()’:
zend/module.h:154:48: error: ‘DL_UNLOAD’ was not declared in this scope
       if (_handle) DL_UNLOAD((DL_HANDLE)_handle);
                                                ^
In file included from zend/includes.h:150:0,
                 from zend/constant.cpp:9:
zend/symbol.h: In instantiation of ‘Php::Symbol<T(Arguments ...)>::Symbol(void*, const char*) [with T = _zend_module_entry*; Arguments = {}]’:
zend/module.h:139:70:   required from here
zend/symbol.h:102:32: error: ‘DL_FETCH_SYMBOL’ was not declared in this scope
         _method(DL_FETCH_SYMBOL((DL_HANDLE)handle, name)) {}
                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [shared/zend/callable.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [shared/zend/base.o] Error 1
In file included from zend/includes.h:150:0,
                 from zend/classimpl.cpp:9:
zend/symbol.h: In constructor ‘Php::Symbol<T(Arguments ...)>::Symbol(void*, const char*)’:
zend/symbol.h:102:56: error: there are no arguments to ‘DL_FETCH_SYMBOL’ that depend on a template parameter, so a declaration of ‘DL_FETCH_SYMBO ’ must be available [-fpermissive]
         _method(DL_FETCH_SYMBOL((DL_HANDLE)handle, name)) {}
                                                        ^
zend/symbol.h:102:56: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from zend/includes.h:151:0,
                 from zend/classimpl.cpp:9:
zend/module.h: In destructor ‘virtual Php::Module::Persistent::~Persistent()’:
zend/module.h:78:32: error: ‘DL_UNLOAD’ was not declared in this scope
                 DL_UNLOAD(*iter);
                                ^
zend/module.h: In member function ‘void Php::Module::Persistent::add(const char*)’:
zend/module.h:102:43: error: ‘DL_LOAD’ was not declared in this scope
             _handles.insert(DL_LOAD(module));
                                           ^
zend/module.h: In constructor ‘Php::Module::Module(const char*, bool)’:
zend/module.h:129:31: error: ‘DL_LOAD’ was not declared in this scope
         _handle = DL_LOAD(path);
                               ^
zend/module.h: In destructor ‘virtual Php::Module::~Module()’:
zend/module.h:154:48: error: ‘DL_UNLOAD’ was not declared in this scope
       if (_handle) DL_UNLOAD((DL_HANDLE)_handle);
                                                ^
zend/classimpl.cpp: In member function ‘zend_object_handlers* Php::ClassImpl::objectHandlers()’:
zend/classimpl.cpp:358:32: error: invalid conversion from ‘void (*)(zval*, zval*, zval*, void**) {aka void (*)(_zval_struct*, _zval_struct*, _zval_struct*, void**)}’ to ‘zend_object_write_property_t {aka _zval_struct* (*)(_zval_struct*, _zval_struct*, _zval_struct*, void**)}’ [-fpermissive]
     _handlers.write_property = &ClassImpl::writeProperty;
                                ^~~~~~~~~~
zend/classimpl.cpp: In static member function ‘static zend_object* Php::ClassImpl::cloneObject(zval*)’:
zend/classimpl.cpp:530:68: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘zend_string* {aka _zend_string*}’ [-Wformat=]
     if (!cpp) zend_error(E_ERROR, "Unable to clone %s", entry->name);
                                                                    ^
zend/classimpl.cpp: In static member function ‘static zend_object* Php::ClassImpl::createObject(zend_class_entry*)’:
zend/classimpl.cpp:1153:74: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘zend_string* {aka _zend_string*}’ [-Wformat=]
     if (!cpp) zend_error(E_ERROR, "Unable to instantiate %s", entry->name);
                                                                          ^
make[2]: *** [shared/zend/classbase.o] Error 1
In file included from zend/includes.h:150:0,
                 from zend/classimpl.cpp:9:
zend/symbol.h: In instantiation of ‘Php::Symbol<T(Arguments ...)>::Symbol(void*, const char*) [with T = _zend_module_entry*; Arguments = {}]’:
zend/module.h:139:70:   required from here
zend/symbol.h:102:32: error: ‘DL_FETCH_SYMBOL’ was not declared in this scope
         _method(DL_FETCH_SYMBOL((DL_HANDLE)handle, name)) {}
                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [shared/zend/constant.o] Error 1
make[2]: *** [shared/zend/classimpl.o] Error 1

================================================================================================================================
I know that PHP-CPP has includes to php package in order to have all those defines.
What could have possibly go wrong by upgradingthe PHP package without changing PHP-CPP at all.
all those "was not declared in this scope" errors...it should be able to include it from the PHP package.
Thanks in advance!

**Comment by adershps** [comment]
Please check the php-cpp release notes in the below link
[https://www.php-cpp.com/download](https://www.php-cpp.com/download)


I can't find any PHP-CPP release support for php 7.4.* in the above link.

**Comment by rozmanro1** [comment]
Yes you are right, i ended up using this commit (7.4PHP support) : 
https://github.com/CopernicaMarketingSoftware/PHP-CPP/commit/da21e3a0bc5afdfeea1cbfe44b16472fc69e135b

and it actually worked out for me.

Thanks!

**Comment by robocoder** [comment]
Fixed in PHP-CPP 2.3.0 (da21e3a0)
