### ISSUE TITLE
Support for PHP 7.2

### ISSUE THREAD

**Issue by sandrokeil** [CopernicaMarketingSoftware/PHP-CPP#359]
Thank you very mich for this awesome project. Have you any plans to support PHP 7.2 soon? I don't know how much work is it. The extension [compiles with Alpine Linux PHP 7.1 ZTS](https://github.com/sandrokeil/event-store-benchmarks/blob/feature/arangodb-php-driver/env/Dockerfile) without any problems but with PHP 7.2.0RC6 I get the following errors:

```
Step 4/7 : RUN git clone --branch ${PHP_CPP_VERSION} https://github.com/CopernicaMarketingSoftware/PHP-CPP /tmp/php-cpp         && cd /tmp/php-cpp         && sed -i 's/`\${PHP_CONFIG} \-\-ldflags`//g' Makefile         && make         && make install
 ---> Running in 6cfe37e283e4
Cloning into '/tmp/php-cpp'...
mkdir -p shared/common
mkdir -p shared/zend
g++ -Wall -c -std=c++11 -fvisibility=hidden -DBUILDING_PHPCPP -Wno-write-strings -MD -g -fpic -o shared/common/modifiers.o common/modifiers.cpp
g++ -Wall -c -std=c++11 -fvisibility=hidden -DBUILDING_PHPCPP -Wno-write-strings -MD -g -fpic -o shared/common/streambuf.o common/streambuf.cpp
g++ -Wall -c -std=c++11 -fvisibility=hidden -DBUILDING_PHPCPP -Wno-write-strings -MD -g `php-config --includes` -fpic -o shared/zend/valueiterator.o zend/valueiterator.cpp
In file included from zend/includes.h:118:0,
                 from zend/valueiterator.cpp:9:
zend/callable.h: In constructor 'Php::Callable::Callable(Php::ZendCallback, const char*, const Arguments&)':
zend/callable.h:55:18: error: 'struct _zend_internal_arg_info' has no member named 'class_name'
         _argv[i].class_name = nullptr;
                  ^~~~~~~~~~
zend/callable.h: In member function 'void Php::Callable::fill(zend_internal_arg_info*, const Php::Argument&) const':
zend/callable.h:171:47: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'class_name'
         if (arg.type() == Type::Object) info->class_name = arg.classname();
                                               ^~~~~~~~~~
zend/callable.h:172:20: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'class_name'
         else info->class_name = nullptr;
                    ^~~~~~~~~~
zend/callable.h:177:43: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'type_hint'
             case Type::Undefined:   info->type_hint = IS_UNDEF;     break;  // undefined means we'll accept any type
                                           ^~~~~~~~~
zend/callable.h:178:43: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'type_hint'
             case Type::Null:        info->type_hint = IS_UNDEF;     break;  // this is likely an error, what good would accepting NULL be? accept anything
                                           ^~~~~~~~~
In file included from zend/includes.h:118:0,
                 from zend/valueiterator.cpp:9:
zend/callable.h:179:43: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'type_hint'
             case Type::False:       info->type_hint = _IS_BOOL;     break;  // accept true as well ;)
                                           ^~~~~~~~~
zend/callable.h:180:43: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'type_hint'
             case Type::True:        info->type_hint = _IS_BOOL;     break;  // accept false as well
                                           ^~~~~~~~~
zend/callable.h:181:43: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'type_hint'
             case Type::Bool:        info->type_hint = _IS_BOOL;     break;  // any bool will do, true, false, the options are limitless
                                           ^~~~~~~~~
zend/callable.h:182:43: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'type_hint'
             case Type::Numeric:     info->type_hint = IS_LONG;      break;  // accept integers here
                                           ^~~~~~~~~
zend/callable.h:183:43: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'type_hint'
             case Type::Float:       info->type_hint = IS_DOUBLE;    break;  // floating-point values welcome too
                                           ^~~~~~~~~
zend/callable.h:184:43: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'type_hint'
             case Type::String:      info->type_hint = IS_STRING;    break;  // accept strings, should auto-cast objects with __toString as well
                                           ^~~~~~~~~
zend/callable.h:185:43: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'type_hint'
             case Type::Array:       info->type_hint = IS_ARRAY;     break;  // array of anything (individual members cannot be restricted)
                                           ^~~~~~~~~
zend/callable.h:186:43: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'type_hint'
             case Type::Object:      info->type_hint = IS_OBJECT;    break;  // must be an object of the given classname
                                           ^~~~~~~~~
zend/callable.h:187:43: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'type_hint'
             case Type::Callable:    info->type_hint = IS_CALLABLE;  break;  // anything that can be invoked
                                           ^~~~~~~~~
zend/callable.h:188:43: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'type_hint'
             default:                info->type_hint = IS_UNDEF;     break;  // if not specified we allow anything
                                           ^~~~~~~~~
zend/callable.h:199:15: error: 'zend_internal_arg_info {aka struct _zend_internal_arg_info}' has no member named 'allow_null'
         info->allow_null = arg.allowNull();
               ^~~~~~~~~~
make: *** [Makefile:204: shared/zend/valueiterator.o] Error 1
```

**Comment by sandrokeil** [comment]
PHP 7.2 is [released](https://secure.php.net/archive/2017.php#id2017-11-30-1)

**Comment by gnat42** [comment]
I started trying to create a patch but am a bit out of my league as to the internal changes in php7.2 I'll see if I can come up with a working patch but I wouldn't hold my breath I'll be able to. 
It would be great to see this working with php7.2

**Comment by CharlotteDunois** [comment]
+1

**Comment by sjinks** [comment]
Submitted a PR (#364). Testers are welcome :-)

**Comment by markkimsal** [comment]
@sjinks  Tested with this project and it works:
https://github.com/lesstif/php-sass
