### PR TITLE
Add support for php7.4

### PR DESCRIPTION
**Pull request by gnat42**
Changes to match the internal changes for PHP 7.4

### CODE REVIEW

**Comment by gnat42** [comment]
There is one issue. Although the extension compiles, classes and their methods are not visible in PHP space. I've confirmed this with the Examples/CppClassesInPhp as well as my own module. I'm not sure why that is the case. I've added Php::Public to all .method() calls but since the class isn't there (as per get_declared_clases()) it doesn't really do anything.

**Comment by gnat42** [comment]
So it looks like some flags have changed, I'm not sure if my solution is the correct fix however I've seen other extensions doing the same with the ce_flags. Instead of assigning directly its bitwise assigned and then the classes are now visible. So either that is the fix or the ClassType constants need to be updated. There is so much different between 7.3 and 7.4 in zend_compile.h I wasn't sure what should be done.

**Comment by gnat42** [comment]
Looks like lots #define's for ZEND_ACC_PUBLIC etc values have changed in this commit: https://github.com/php/php-src/commit/0fbd2e6a168a5cfacec6c44f4c179879a52428f3#diff-bb1c0392a5de04576925c02a7c078dc1

So I'm guessing my |= (int)_type; is incorrect and what actually needs to happen is a change to classtype.h however when looking at zend_compile.h I can't 100% be sure that the numbers set there correspond to the old zend_compile.h. I think this is the last thing to solve for this to work with php 7.4.

Some insight would be great. Even comments in classtype.h on how the values were calculated or what constants they were derived from would be great.

**Comment by gnat42** [comment]
Ok, so I've dug a bit more and found the root cause of the issue.

In PHP 7.4 zend_API.c the function that registers classes there are a number of [constants](https://github.com/php/php-src/blob/PHP-7.4/Zend/zend_API.c#L2682) being or'd. 

In PHP 7.3 zend_API.c has fewer options being [set](https://github.com/php/php-src/blob/PHP-7.3/Zend/zend_API.c#L2723). 

So perhaps my |= (int)_type; may be the appropriate solution. However its also possible that the ClassType values are updated to the combination of their value and the defaults in the zend_API.c

**Comment by iMbell** [comment]
`mkdir -p shared/common
mkdir -p shared/zend
g++ -Wall -c -std=c++11 -fvisibility=hidden -DBUILDING_PHPCPP -Wno-write-strings -MD -g `php-config --includes` -fpic -o shared/zend/classimpl.o zend/classimpl.cpp
zend/classimpl.cpp: In static member function ‘static int Php::ClassImpl::getClosure(zval*, zend_class_entry**, zend_function**, zend_object**)’:
zend/classimpl.cpp:307:35: error: ‘zend_empty_string’ was not declared in this scope
     function->function_name     = zend_empty_string;            // should not be null, as this is free'ed by zend when doing exception handling
                                   ^
make: *** [shared/zend/classimpl.o] Error 1`

why

**Comment by gnat42** [comment]
I'm not sure why that is there, I've noticed it but haven't dug into it

**Comment by gnat42** [comment]
So I dug a bit more and it looks like I was confusing the class visibility with the method visibility. I need to look at modifiers.cpp I think.

**Comment by scorninpc** [comment]
I confirmed with last dev src

```
$ php -dextension=./test.so test.php 
PHP Warning:  Invalid access level for Class1::__construct() - access must be exactly one of public, protected or private in Unknown on line 0
PHP Warning:  Invalid access level for Class1::method1() - access must be exactly one of public, protected or private in Unknown on line 0
OK

$php -v
PHP 7.4.0-dev (cli) (built: Oct  2 2019 22:33:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0-dev, Copyright (c) Zend Technologies

$
```

```
#include <phpcpp.h>

class Class1 : public Php::Base
{
	public:
		Class1() = default;
		~Class1() = default;
		
		void __construct() { printf("__construct\n"); }
		
		void method1() { printf("method1\n"); }
};

extern "C" {
	
    PHPCPP_EXPORT void *get_module() 
    {
        // Register
        static Php::Extension extension("test", "1.0");
        
        // Create class
		Php::Class<Class1> class1("Class1");
			class1.method<&Class1::__construct>("__construct");
            class1.method<&Class1::method1>("method1");

		extension.add(std::move(class1));
		
        // return
        return extension;
    }
}
```

I'm investigating why too. You got a nice direction. However, your changes works fine

**Comment by gnat42** [comment]
Hey @scorninpc yeah so I've re-pushed with my latest changes. It doesn't *fix* the issue but I think is required. I've based it off the difference of Zend/zend_compile.h in php from 7.3 to 7.4 branch.

https://pastebin.com/FXBPt7U1

This shows that PHP changed the values for public, protected, private etc. However with this change I still get the errors. I haven't tracked the code setting the actual php visibility flag for a class method but the error message you get on the console will take you to where it is issued in the php-cpp file. I haven't had time to finish looking at that. 

Any additional insight/help on this would be awesome

**Comment by scorninpc** [comment]
Thank you to start it. I'v small time too, but i'm investigating the php-src. I'v see this change on constant of visibility types, changed, but nothing to.

I'll keep you alive

**Comment by danog** [comment]
The visibility modifiers for PHP 7.4 weren't applied  because the PHP_VERSION_ID constant wasn't defined for files in the  common target. PR https://github.com/NobletSolutions/PHP-CPP/pull/1 fixes the issue by using the appropriate include flags and including the php header files.

**Comment by gnat42** [comment]
@danog's patch indeed fixes the issue for me. I've incorporated it, squashed it and pushed here. Our CI now seems to work with PHP74 and the extension we wrote based off php-cpp...  Merging this would be great with a new patch release.

**Comment by TheROPFather** [comment]
@gnat42 Trying to build this, however I receive many compilation errors.

`g++ -Wall -c -std=c++11 -fvisibility=hidden -DBUILDING_PHPCPP -Wno-write-strings -MD -g 'php-config --includes' -fpic -o shared/zend/inivalue.o zend/inivalue.cpp
In file included from zend/includes.h:120,
                 from zend/inivalue.cpp:8:
zend/callable.h: In constructor ‘Php::Callable::Callable(Php::ZendCallback, const char*, const Arguments&)’:
zend/callable.h:56:18: error: ‘struct _zend_internal_arg_info’ has no member named ‘is_variadic’
`

I've attached a full build log here: https://pastebin.com/MGpWKVSd

`
PHP 7.4.0 (cli) (built: Nov 30 2019 10:43:49) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.8.1, Copyright (c) 2002-2019, by Derick Rethans
`
 Any thoughts?

**Comment by gnat42** [comment]
I can't say I've ever seen an error like that in trying to get this to build against php 7.4.0.

I just rebuilt php-cpp against 7.4.0 without issues. I've pasted the patch I was using and the build logs:

Build Log: https://pastebin.com/0DzU9bLw
Patch: https://pastebin.com/jTMVmzCM

**Comment by scorninpc** [comment]
Works a lot fine, why no merge?

image

**Comment by danog** [comment]
Ping please merge

**Comment by DerAlSem** [comment]
Please, merge, we do need 7.4 support, your work is highly appreciated.

**Comment by stereomatchingkiss** [comment]
Is this project dead?

**Comment by scorninpc** [comment]
This project are dead by author, but people are making that work. I think someone need to create a new project to make that updated. I'm non-git user, so if anyone can to that better, i help

**Comment by jpuck** [comment]
This branch works very well thank you! :bow:

**Comment by scorninpc** [comment]
The dev is away alot time. I'm mergeing branchs here https://github.com/scorninpc/PHP-CPP until the author appears

**Comment by yaroslavche** [comment]
> The dev is away alot time. I'm mergeing branchs here https://github.com/scorninpc/PHP-CPP until the author appears

It is a pity that the author went into inactive, I hope he is doing well.

@scorninpc I've used the fork in the extension, and everything seems to be working fine.
https://travis-ci.com/yaroslavche/phptdlib/jobs/283203070
```
$ php --version
PHP 7.4.3-dev (cli) (built: Jan 23 2020 12:06:04) ( ZTS )
```
Could you check also #399 please?

**Comment by DerAlSem** [comment]
> The dev is away alot time. I'm mergeing branchs here https://github.com/scorninpc/PHP-CPP until the author appears

Man, you're awesome. Rebuilt php-tdlib with your fork. Works like a charm.

**Comment by scorninpc** [comment]
> > The dev is away alot time. I'm mergeing branchs here https://github.com/scorninpc/PHP-CPP until the author appears
> 
> Man, you're awesome. Rebuilt php-tdlib with your fork. Works like a charm.

Thank you, but i'm only a "merger" hahhhah, thanks for all community. When main dev appear I send only one pull request

**Comment by mlocati** [comment]
@EmielBruijntjes Any plans for a new release with this patch applied?
