### PR TITLE
Php73 Support

### PR DESCRIPTION
**Pull request by gnat42**
Hello,

  This PR adds support for PHP 7.3. There are two very very very bizarre changes that I'm not 100% sure of at the moment. I'll note them in the PR, though one of them is a single commit 5664c18.

  Everything compiles with these changes. Though those two changes should be reviewed by someone with greater knowledge of what is going on. One is definitely some kind of weird compiler bug.

### CODE REVIEW

File: zend/classimpl.cpp [hunk 1]
```diff
@@ -1354,7 +1354,9 @@ zend_class_entry *ClassImpl::initialize(ClassBase *base, const std::string &pref
     {
         // install iterator functions
         entry.get_iterator = &ClassImpl::getIterator;
+#if PHP_VERSION_ID < 70300
         entry.iterator_funcs.funcs = IteratorImpl::functions();
```
Comment (gnat42) [inline zend/classimpl.cpp]: I wasn't sure if it was no longer required as the details in the php README.internals wasn't very clear to me.

File: zend/value.cpp [hunk 2]
```diff
@@ -401,7 +406,7 @@ Value& Value::operator=(struct _zval_struct* value)
         {
             // If reference count is greater than 1, we need to separate zval
             // This is the optimized version of SEPARATE_ZVAL_NOREF()
-            if (Z_COPYABLE_P(to))
+            if (Z_COPYABLE_P(to)))
```
Comment (gnat42) [inline zend/value.cpp]: Without this ridiculous addition I would get a compiler error:
```
zend/value.cpp:410:13: error: expected ')' before '{' token
```
However I couldn't figure out how it got to be so wrong.

**Comment by gnat42** [comment]
I should note, this compiles on CentOS 7, against php7.3 using GCC 6.3.1

File: zend/value.cpp (hunk 2 above)
Comment (mvdwerve) [reply zend/value.cpp]: It's probably a bug...

`#define Z_COPYABLE(zval)			((Z_TYPE(zval) == IS_ARRAY)`

[I've opened a bug on the PHP bug tracker.](https://bugs.php.net/bug.php?id=76820)

File: zend/classimpl.cpp (hunk 1 above)
Comment (mvdwerve) [reply zend/classimpl.cpp]: I think they are still required, but they have to be allocated now, as there is a iterator_funcs_ptr in place of this function. However, that iterator_funcs_ptr does not contain `funcs`, so something else has changed there.

File: zend/value.cpp (hunk 2 above)
Comment (mvdwerve) [reply zend/value.cpp]: My fix has been merged into the engine so I'm going to resolve conflicts and merge this in.
